### ISSUE TITLE
drake-store.service.d.ts: no exported member 'DragulaOptions

### ISSUE THREAD

**Issue by sa1509** [swimlane/ngx-dnd#111] opened 2018-08-03 02:18 UTC
I've added the ngx-dnd using the following command:
npm i @swimlane/ngx-dnd @swimlane/dragula --save
npm i @types/dragula --save

And then imported NgxDnDModule to my app.module.

Now when I execute ng build I get this error:
"ERROR in node_modules/@swimlane/ngx-dnd/lib/services/drake-store.service.d.ts(19,44): error TS2694: Namespace ''*'' has no exported member 'DragulaOptions'."

**Comment by MalithHatananchchige** [comment] 2018-08-07 13:59
Having the same issue.

**Comment by dlcwalkoff** [comment] 2018-08-22 13:32
@sa1509 may look my [hack](https://github.com/swimlane/ngx-dnd/issues/82#issuecomment-415030200)

**Comment by Hypercubed** [comment] 2018-10-29 16:14
I still unable to reproduce this issue. Has anyone tried installing @types/dragula in your project?

**Comment by Hypercubed** [comment] 2019-04-18 17:02
I'm hopefull this is fixed in v8... if not please reopen.

**Closed by Hypercubed** 2019-04-18 17:02 UTC
Labels: dump dragula, investigate

**Comment by warlockdn** [comment] 2021-02-13 05:27
Still getting this error. 

"@swimlane/dragula": "^3.8.0",
"@swimlane/ngx-dnd": "^8.2.0",
"@types/dragula": "^3.7.0"

any permanent fix yet ?
