### ISSUE TITLE
Angular 6: Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Gerros** [swimlane/ngx-dnd#81] opened 2018-05-18 12:38 UTC
```
[x] bug report
```

**Current behavior**
After upgrading to angular 6 and making a production build my application does not work anymore and in the console of the browser following error appears:
Uncaught ReferenceError: global is not defined

**Expected behavior**
Application works without errors

**Reproduction of the problem**
I am using version 4.0.1 of swimline ngx-dnd and angular 6.0.2, it works with ng serve, but not with a production build
Create a new Angular Project with the Angular cli (6.0.3), ng new mytest, add the swimlane dnd library (4.0.1) and use e.g. the ngx-dnd-container component in the template, make a prod build and open the app

This is a known issue after upgrading to angular 6:
https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Comment by ssuperczynski** [comment] 2018-05-23 18:26
I was able to reproduce it. Fixing #84 created error #86. By fixing #86 now it shows:

```
Uncaught ReferenceError: global is not defined
    at Object../node_modules/custom-event/index.js (index.js:2)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/crossvent/src/crossvent.js (crossvent.js:3)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@swimlane/dragula/dragula.js (dragula.js:4)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@swimlane/ngx-dnd/release/src/services/drake-store.service.js (drake-store.service.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@swimlane/ngx-dnd/release/src/directives/ngx-droppable.directive.js (ngx-droppable.directive.js:1)
    at __webpack_require__ (bootstrap:76)
```

**Comment by mhmo91** [comment] 2018-05-24 20:49
same problem here once i use `import 'intl';` in polyfills

**Comment by tobias74** [comment] 2018-05-29 09:46
I had the same issue. As proposed in https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833 you can just initialize global to the window-object.

But for me the problem was, that all the imports in polyfill.ts were hoisted and executed before I could initialize 

`(window as any).global = window;`

**Solution:**

I put this line in a new empty file called "global-shim.ts" and imported it at the very top of polyfill.ts:

`import 'global-shim';`

**Comment by turgodi** [comment] 2018-06-09 18:59
The fix gives me some weird errors.

zone.js:2969 GET http://localhost:4200/container.component.html 404 (Not Found)
zone.js:2969 GET http://localhost:4200/item.component.html 404 (Not Found)

And the application does not start anymore.
It's sad to see not a single drag and drop library supports Angular 6

**Comment by Gerros** [comment] 2018-06-09 19:12
the "fix" to add the global yourself is just a workaround... would be nice, if we could get a proper solution/fix... for more information: 
https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Comment by Hypercubed** [comment] 2018-06-19 16:30
@Gerros @ssuperczynski @tobias74 @turgodi Can any of you please try the next version and let us know if that fixes your issue: `npm install @swimlane/ngx-dnd@next`

**Comment by ssuperczynski** [comment] 2018-06-19 17:49
@Hypercubed I can confirm my app compiled correctly with ngx-dnd under angular6.
But I had to put `(window as any).global = window;` in the polyfills.ts as @tobias74 mentioned above.
Without polyfills modified errors appears in the Chrome console:

```
index.js:2 Uncaught ReferenceError: global is not defined
    at Object../node_modules/custom-event/index.js (index.js:2)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/crossvent/src/crossvent.js (crossvent.js:3)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@swimlane/dragula/dragula.js (dragula.js:4)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@swimlane/ngx-dnd/fesm5/swimlane-ngx-dnd.js (dragula.js:618)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/ngx-easy-table/components/base/base.module.ts (base.component.ts:33)
    at __webpack_require__ (bootstrap:76)
```

**Comment by Hypercubed** [comment] 2018-06-19 18:51
I'll need to look deeper... looks like a bug in dragula/crossvent/custom-event

**Comment by kemalbirinci** [comment] 2018-06-21 07:36
adding this line in to **pollyfills.ts** fixed my problem

`(window as any).global = window;`

**Comment by Gerros** [comment] 2018-06-21 07:37
@kemalbirinci no, this does not FIX the problem... please read the thread

**Comment by adammendoza** [comment] 2018-07-02 02:39
@Hypercubed I just installed the package and got this error.

**Comment by zolakt** [comment] 2018-07-05 12:33
I'm getting a similar error on, but "document is not defined", on Angular 6 with SSR, as soon as I include the package.

CSR works fine, so I can get to a page that uses this lib, but I can't reload it, or load it initially.
I can pollyfill the document variable, but that messes up some other libs.

This should be fixed. Since the whole functionality has nothing to do with SSR, simply if/else-ing stuff like widow/global/document should suffice.

**Comment by adammendoza** [comment] 2018-07-05 22:06
fwiw: The fix from @tobias74 commented on May 29 • worked for me.

**Comment by yulm6** [comment] 2018-07-09 07:19
When I add sockjs-client, I got the same issue.
`npm install sockjs-client --save`

I did as  @tobias74 ,maybe it worked,but the brower refreshes frequenly.

**Comment by marcionitao** [comment] 2018-08-12 07:08
It worked for me.
`<script>
  if (global === undefined) {
    var global = window;
  }
</script>`

https://github.com/aws-amplify/amplify-js/issues/678

**Comment by brunobertechini** [comment] 2018-09-20 07:41
Why is this closed? What is the final solution ?

**Comment by Hypercubed** [comment] 2018-09-20 16:42
@brunobertechini Untill we replace dragula please use the `if (global === undefined) { var global = window; }` solution.  You can do this in your pollyfills.ts

**Comment by turgodi** [comment] 2018-10-05 17:53
To me the final solution was using an other library.
https://github.com/RubaXa/Sortable worked great.

**Comment by Hypercubed** [comment] 2018-10-29 16:12
I'll be updating the docs to call this out.

**Closed by Hypercubed** 2018-10-29 16:12 UTC
Labels: dump dragula

**Comment by athiraaravindan** [comment] 2018-11-09 04:59
> adding this line in to **pollyfills.ts** fixed my problem (just a workaround as @Gerros said)
> 
> `(window as any).global = window;`

not worked for me please suggest another
 solution

**Comment by wbhob** [comment] 2018-11-09 22:43
So the Ng Material team just dropped a really good drag and drop implementation, if you're still having problems, I highly recommend it: https://material.angular.io/cdk/drag-drop/overview

**Comment by 1011RKP** [comment] 2019-01-18 17:00
<script>
    if (global === undefined) {
      var global = window;
    }
  </script>

**Comment by shubhamchhapre30** [comment] 2019-01-28 09:47
This issue in development phase also. any perfect solution for it.

**Comment by zensarCompass** [comment] 2019-05-21 08:16
> I had the same issue concerning the
> 
> > import 'intl';
> 
> in polyfills. The solution proposed in [angular/angular-cli#8160 (comment)](https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833) did not fully resolve my situation.
> 
> For me the problem was that all the imports in polyfill.ts were hoisted and executed before I could initialize
> 
> `(window as any).global = window;`
> 
> **Solution:**
> 
> I put the above line
> 
> `(window as any).global = window;`
> 
> in a new empty file called "global-shim.ts" and imported it at the very top of polyfill.ts:
> 
> `import 'global-shim';`

This solution worked for me in Angular 7 project

**Comment by danieldanielecki** [comment] 2019-08-15 09:12
In case, if your **target** is **node** in webpack (`target: 'node'`), because you want to fix `"Can't resolve 'fs'`. Then you're getting the following error `Fix: "Uncaught ReferenceError: global is not defined"` do it as follows `node: { global: true, fs: 'empty' }`. **Bonus**: if you got error `"Uncaught ReferenceError: exports is not defined".` simply add `libraryTarget: 'umd'`. The complete webpack config code is below.

```
const webpackConfig = {
  node: { global: true, fs: 'empty' }, // Fix: "Uncaught ReferenceError: global is not defined", and "Can't resolve 'fs'".
  output: {
    libraryTarget: 'umd' // Fix: "Uncaught ReferenceError: exports is not defined".
  }
};

module.exports = webpackConfig; // Export all custom Webpack configs.
```

**Comment by varunkumar2233** [comment] 2019-09-02 19:16
there is something you have imported and not using in you app
